import type { RenderJobData, RenderOutput, RenderRequest, RenderStatus, WorkerHeartbeat } from "../types";
import type { RenderingDb } from "./supabase";

export async function assertRenderAccess(client: RenderingDb, workspaceId: string, userId: string) { const { data, error } = await (client as any).from("workspace_members").select("id").eq("workspace_id", workspaceId).eq("user_id", userId).is("deleted_at", null).maybeSingle(); if (error) throw error; if (!data) throw new Error("Workspace render access required"); }
export async function createRenderJobRecord(client: RenderingDb, request: RenderRequest) { const { data, error } = await (client as any).from("render_jobs").insert({ workspace_id: request.workspaceId, project_id: request.projectId ?? null, requested_by: request.requestedBy, kind: request.kind, status: "queued", priority: request.priority, payload: request, progress: 0 }).select("id").single(); if (error) throw error; return (data as { id: string }).id; }
export async function updateRenderJob(client: RenderingDb, id: string, patch: { status?: RenderStatus; progress?: number; error?: string; workerId?: string; output?: RenderOutput }) { const value: Record<string, unknown> = { updated_at: new Date().toISOString() }; if (patch.status) value.status = patch.status; if (patch.progress !== undefined) value.progress = patch.progress; if (patch.error !== undefined) value.error_message = patch.error; if (patch.workerId) value.worker_id = patch.workerId; if (patch.output) value.result = patch.output; if (patch.status === "active") value.started_at = new Date().toISOString(); if (patch.status === "completed" || patch.status === "failed") value.completed_at = new Date().toISOString(); const { error } = await (client as any).from("render_jobs").update(value).eq("id", id); if (error) throw error; }
export async function recordRenderOutput(client: RenderingDb, jobId: string, output: RenderOutput) { const { error } = await (client as any).from("render_outputs").insert({ render_job_id: jobId, bucket: output.bucket, storage_path: output.path, signed_url: output.signedUrl, mime_type: output.mimeType, size_bytes: output.sizeBytes, width: output.width ?? null, height: output.height ?? null, duration_ms: output.durationMs ?? null, format: output.format }); if (error) throw error; }
export async function recordRenderMetric(client: RenderingDb, jobId: string, name: string, value: number, unit: string) { const { error } = await (client as any).from("render_metrics").insert({ render_job_id: jobId, metric_name: name, metric_value: value, unit }); if (error) throw error; }
export async function heartbeat(client: RenderingDb, beat: WorkerHeartbeat) { const { error } = await (client as any).from("render_workers").upsert({ worker_id: beat.workerId, pool: beat.pool, hostname: beat.hostname, version: beat.version, concurrency: beat.concurrency, gpu_enabled: beat.gpuEnabled, status: beat.status, last_heartbeat_at: new Date().toISOString() }, { onConflict: "worker_id" }); if (error) throw error; const { error: healthError } = await (client as any).from("worker_health").insert({ worker_id: beat.workerId, status: beat.status, metrics: beat }); if (healthError) throw healthError; }
