import { getQueueMetrics } from "@canva-ai/rendering/api";
import { createSupabaseServerClient } from "../../lib/supabase/server";
import { VideoExportClient } from "./VideoExportClient";

export default async function RenderDashboard({ searchParams }: { searchParams?: Promise<Record<string, string | string[] | undefined>> }) {
  const params = await searchParams; const workspaceParam = params?.workspaceId; const workspaceId = Array.isArray(workspaceParam) ? workspaceParam[0] : workspaceParam;
  const db = await createSupabaseServerClient();
  const [video, thumbnail, transcode] = await Promise.all([getQueueMetrics("video").catch((error) => ({ kind: "video", error: error.message, counts: {} })), getQueueMetrics("thumbnail").catch((error) => ({ kind: "thumbnail", error: error.message, counts: {} })), getQueueMetrics("transcode").catch((error) => ({ kind: "transcode", error: error.message, counts: {} }))]);
  const { data: jobs } = workspaceId ? await (db as any).from("render_jobs").select("*").eq("workspace_id", workspaceId).order("created_at", { ascending: false }).limit(20) : { data: [] };
  const { data: workers } = await (db as any).from("render_workers").select("*").order("last_heartbeat_at", { ascending: false }).limit(50);
  return <main className="min-h-screen bg-slate-100 p-6 text-slate-950"><div className="mx-auto grid max-w-6xl gap-6"><header className="rounded-3xl bg-slate-950 p-8 text-white"><p className="text-sm font-bold uppercase tracking-[0.2em] text-cyan-300">Distributed rendering</p><h1 className="mt-2 text-4xl font-black">Render queue dashboard</h1><p className="mt-2 text-slate-300">Queue states, worker health, retry/dead-letter visibility, and video exports.</p></header><VideoExportClient workspaceId={workspaceId ?? ""} /><section className="grid gap-4 md:grid-cols-3">{[video, thumbnail, transcode].map((metric: any) => <div className="rounded-2xl bg-white p-5 shadow" key={metric.kind}><h2 className="font-black">{metric.kind}</h2>{metric.error ? <p className="text-sm text-red-600">{metric.error}</p> : <pre className="mt-3 text-xs">{JSON.stringify(metric.counts, null, 2)}</pre>}</div>)}</section><section className="rounded-2xl bg-white p-6 shadow"><h2 className="text-xl font-black">Worker status</h2><div className="mt-3 grid gap-2">{(workers ?? []).map((w: any) => <div className="flex justify-between rounded-xl bg-slate-50 p-3" key={w.worker_id}><span>{w.worker_id}</span><strong>{w.status}</strong></div>)}</div></section><section className="rounded-2xl bg-white p-6 shadow"><h2 className="text-xl font-black">Render history</h2><div className="mt-3 grid gap-2">{(jobs ?? []).map((j: any) => <div className="rounded-xl bg-slate-50 p-3" key={j.id}><div className="flex justify-between"><strong>{j.kind}</strong><span>{j.status} · {j.progress}%</span></div>{j.error_message ? <p className="text-sm text-red-600">{j.error_message}</p> : null}</div>)}</div></section></div></main>;
}
