"use client";
import { useState } from "react";

const sampleTimeline = (width: number, height: number) => ({ id: crypto.randomUUID(), width, height, fps: 30, scenes: [{ id: "intro", name: "Intro", durationMs: 3000, background: "#0f172a", layers: [{ id: "title", type: "text", text: "Canva AI Render", x: 120, y: 160, width: 900, height: 120, fill: "#67e8f9", startMs: 0, durationMs: 3000, zIndex: 1, opacity: 1, animations: [{ property: "x", keyframes: [{ timeMs: 0, value: -600, easing: "ease-out" }, { timeMs: 900, value: 120, easing: "ease-out" }] }] }, { id: "shape", type: "shape", shape: "rect", x: 100, y: 320, width: 760, height: 16, fill: "#22d3ee", startMs: 0, durationMs: 3000, zIndex: 0, opacity: 1, animations: [] }] }] });

export function VideoExportClient({ workspaceId = "" }: { workspaceId?: string }) {
  const [workspace, setWorkspace] = useState(workspaceId); const [format, setFormat] = useState<"mp4" | "webm">("mp4"); const [jobId, setJobId] = useState<string | null>(null); const [status, setStatus] = useState("idle");
  async function startRender() { setStatus("queueing"); const response = await fetch("/api/render/jobs", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ workspaceId: workspace, kind: "video", timeline: sampleTimeline(1280, 720), output: { format, filename: `timeline-${Date.now()}`, quality: "standard", transparent: false } }) }); const payload = await response.json(); if (!response.ok) return setStatus(payload.error ?? "failed"); setJobId(payload.renderJobId); poll(payload.renderJobId); }
  async function poll(id: string) { for (;;) { await new Promise((r) => setTimeout(r, 1500)); const response = await fetch(`/api/render/jobs/${id}`, { cache: "no-store" }); const payload = await response.json(); setStatus(`${payload.status ?? "queued"} · ${payload.progress ?? 0}%`); if (["completed", "failed", "dead_letter"].includes(payload.status)) break; } }
  return <section className="rounded-2xl bg-white p-6 shadow"><h2 className="text-xl font-black">Video export modal</h2><div className="mt-4 grid gap-3 md:grid-cols-3"><input className="rounded-xl border p-3" placeholder="Workspace UUID" value={workspace} onChange={(e) => setWorkspace(e.target.value)} /><select className="rounded-xl border p-3" value={format} onChange={(e) => setFormat(e.target.value as "mp4" | "webm")}><option value="mp4">MP4 / H264</option><option value="webm">WebM / VP9</option></select><button className="rounded-xl bg-slate-950 px-4 py-3 font-bold text-white disabled:opacity-50" disabled={!workspace || status === "queueing"} onClick={startRender}>Render timeline</button></div><p className="mt-3 text-sm text-slate-600">Status: {status}{jobId ? ` · ${jobId}` : ""}</p></section>;
}
